# Numpy - (Numerical Python)
### NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++ .It is used for working with arrays called ndarray. It also has functions for working in domain of linear algebra, fourier transform, and matrices.

## Why Numpy

## 1) Memory Usage
### NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.This behavior is called locality of reference in computer science.

In [1]:
import numpy as np
import time 
import sys 

array = np.arange(100)
print("The size of the Numpy array here is:", array.size*array.itemsize)

The size of the Numpy array here is: 400


In [2]:
list_ = range(0,100)
sys.getsizeof(1)#Return the size of an object in bytes

28

In [3]:
print("The size of the list here is:",sys.getsizeof(1)*len(list_))

The size of the list here is: 2800


## 2) Faster!! 
### In Python we have lists that serve the purpose of arrays, but they are slow to process.
### NumPy aims to provide an array object that is up to 50x faster that traditional Python lists.

In [4]:
size = 100000

#Create 2 lists of size 1lakh
list1 = range(size)
list2 = range(size)

#Create 2 arrays of the same size 
arr1 = np.arange(size)
arr2 = np.arange(size)

In [5]:
start = time.time()
for x,y in zip(list1,list2):
    res = x+y
print("The total time taken for execution is:",(time.time()-start)*1000)

The total time taken for execution is: 19.999980926513672


In [6]:
start = time.time()
res = arr1+arr2
print("The total time taken for execution is:",(time.time()-start)*1000)

The total time taken for execution is: 0.0


## Convienient 

In [7]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

print("The addition: ",a1+a2)
print("The subtraction: ",a1-a2)
print("The multiplication: ",a1*a2)

The addition:  [5 7 9]
The subtraction:  [-3 -3 -3]
The multiplication:  [ 4 10 18]


###  Practice Numpy

In [8]:
'''
Install 
!pip install numpy 
!conda install numpy --y
!pip3 install numpy
'''

'\nInstall \n!pip install numpy \n!conda install numpy --y\n!pip3 install numpy\n'

In [9]:
# Import numpy 
import numpy as np

In [10]:
from numpy import array
"""
Using import numpy, all sub-modules and functions in the numpy module can only be accessed in the numpy.* namespace. 
    e.g: numpy.array([1,2,3]).
Using import numpy as np, an alias for the namespace will be created. 
    e.g: np.array([1,2,3]).
Using from numpy import *, all functions will be loaded into the local namespace.
     e.g:array([1,2,3]) can then be used. 
"""

'\nUsing import numpy, all sub-modules and functions in the numpy module can only be accessed in the numpy.* namespace. \n    e.g: numpy.array([1,2,3]).\nUsing import numpy as np, an alias for the namespace will be created. \n    e.g: np.array([1,2,3]).\nUsing from numpy import *, all functions will be loaded into the local namespace.\n     e.g:array([1,2,3]) can then be used. \n'

In [11]:
a1 = np.array([1,2,28])#convering list into ndarray
print(a1)

[ 1  2 28]


In [12]:
a2 = np.array((1,2,28))#convering tuple into ndarray
print(a2)

[ 1  2 28]


In [13]:
a3 = np.array({ "brand": "Ford",  "model": "Mustang",  "year": 1964})#convering dict into ndarray
print(a3)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}


In [14]:
a1

array([ 1,  2, 28])

In [15]:
a2

array([ 1,  2, 28])

In [16]:
a3

array({'brand': 'Ford', 'model': 'Mustang', 'year': 1964}, dtype=object)

In [17]:
a1.dtype

dtype('int32')

In [18]:
a3.dtype #Str is considered as obj in dtype

dtype('O')

In [19]:
type(a1)#same O/P for a2,a3

numpy.ndarray

In [20]:
arr=np.array([1.0,2.0,3,0.2,10,10])
print("Size of the array:",arr.size)
print("Length of one array element in bytes:",arr.itemsize)
print("Total bytes consumed by the elements of the array:",arr.nbytes)

Size of the array: 6
Length of one array element in bytes: 8
Total bytes consumed by the elements of the array: 48


In [21]:
arr
#Since some elements are float and int, it automatically typecasts to to float

array([ 1. ,  2. ,  3. ,  0.2, 10. , 10. ])

In [22]:
arr1=np.array([1.0,2.0,3,0.2,10,10,"strr"])
#Since some elements are float,str and int, it automatically typecasts to to str-typecasts to higher(largest) datatype
arr1

array(['1.0', '2.0', '3', '0.2', '10', '10', 'strr'], dtype='<U32')

In [23]:
print("Unique elements of the above array:")
print(np.unique(arr))

Unique elements of the above array:
[ 0.2  1.   2.   3.  10. ]


In [24]:
arr2=np.arange(0,10)#Similar to range in python
print(arr2)

[0 1 2 3 4 5 6 7 8 9]


In [25]:
arr2[2]

2

In [26]:
arr2%3

array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0], dtype=int32)

In [27]:
arr2.sum()

45

In [28]:
arr2.shape

(10,)

In [29]:
arr2=arr2.reshape(2,5)

In [30]:
arr2.shape

(2, 5)

In [31]:
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [32]:
tup=(1,3,4,2)
a=np.array(tup)#Converting tuple to numpy array
a

array([1, 3, 4, 2])

'''
N-D - Stands for 'N'-Dimentional Array
'''
1-D Matrix - Rows
2-D Matrix - Rows,columns
3-D Matrix (Tensors) - Rows,columns and depth

In [33]:
lst = [1,2,"batch14"]
type(lst[1])

int

In [34]:
lst = [1,2,"batch14"]
type(lst[2])

str

In [35]:
arr = np.array([1,2,3,"Batch14"])
print(type(arr[0]))

<class 'numpy.str_'>


In [36]:
arr = np.array([1,2,3,"Batch14"])
print(type(arr[2]))

<class 'numpy.str_'>


In [37]:
print(np.__version__)

1.16.4


In [38]:
arr.shape

(4,)

In [39]:
arr_2d = np.array([[1,2,3],[5,6,7]])

In [40]:
arr_2d

array([[1, 2, 3],
       [5, 6, 7]])

In [41]:
arr_2d[1][1]

6

In [42]:
arr_2d.shape

(2, 3)

In [43]:
arr_2d[1:,:2]

array([[5, 6]])

In [44]:
#concatenation

arr1=np.array([10,20,30])
arr2=np.array([40,50,60])
print("Array1:",arr1)
print("Array2:",arr2)
convertedArray=np.concatenate((arr1,arr2))
print("Converted array",convertedArray)

Array1: [10 20 30]
Array2: [40 50 60]
Converted array [10 20 30 40 50 60]


1) Create a 2d Array with shape 3X3 with numpy

2) Create a 3d Array of shape 1X4X3 with numpy

In [45]:
array_3d = np.array([[[1,5,7],[4,5,6],[7,8,9],[8,9,10]],[[1,15,17],[14,15,16],[17,18,19],[8,9,10]]])

In [46]:
array_3d

array([[[ 1,  5,  7],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [ 8,  9, 10]],

       [[ 1, 15, 17],
        [14, 15, 16],
        [17, 18, 19],
        [ 8,  9, 10]]])

In [47]:
array_3d.shape

(2, 4, 3)

In [48]:
array_3d = np.array([[[1,5,7],[4,5,6],[7,8,9],[8,9,10]],[[1,5,7],[4,5,6],[7,8,9],[8,9,10]]])

In [49]:
array_3d

array([[[ 1,  5,  7],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [ 8,  9, 10]],

       [[ 1,  5,  7],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [ 8,  9, 10]]])

In [50]:
array_3d.shape

(2, 4, 3)

## Functions involved in creating an array

In [51]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
a = a.reshape((1,4,4))

In [52]:
#Reshape: translates or converts the shape of the array 
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [53]:
#linspace: This function generates elements which are equally spaced from each other!
np.linspace(0.50,50.45,10) #---> Start, Stop and Number of elements(Equally spaced)

array([ 0.5 ,  6.05, 11.6 , 17.15, 22.7 , 28.25, 33.8 , 39.35, 44.9 ,
       50.45])

In [54]:
np.arange(10,90,10)

array([10, 20, 30, 40, 50, 60, 70, 80])

In [55]:
np.arange(15,9,-1)

array([15, 14, 13, 12, 11, 10])

In [56]:
#arange: Generated values based on the 'Step' you specify between start and stop
np.arange(90,10,-10) # --> Start, Stop and Step 

array([90, 80, 70, 60, 50, 40, 30, 20])

In [57]:
lst = list(range(0,100))

In [58]:
lst[0:90:10]

[0, 10, 20, 30, 40, 50, 60, 70, 80]

## Create an array with values from 68 - 24 (just the even numbers)

In [59]:
#Zeros - Fills the specified shape with zeros
np.zeros((2,3))#returns float by default

array([[0., 0., 0.],
       [0., 0., 0.]])

In [60]:
#Ones - fills the specified shape with ones
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [61]:
[[1,1,1],
 [1,1,1,],
 [1,1,1,]]

[[1, 1, 1], [1, 1, 1], [1, 1, 1]]

In [62]:
[[0,0,0,0,0],
 [0,1,1,1,0],
 [0,1,1,1,0],
 [0,1,1,1,0],
 [0,0,0,0,0]]

[[0, 0, 0, 0, 0],
 [0, 1, 1, 1, 0],
 [0, 1, 1, 1, 0],
 [0, 1, 1, 1, 0],
 [0, 0, 0, 0, 0]]

In [63]:
a = np.zeros((5,5))
a[1:4,1:4] =1

In [64]:
a

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

### Padding - np.pad(array, pad_width, mode, **kwargs)
#### Used to pad/add constant values in the array width is the surrounding area around the array

In [65]:
a = np.ones((3,3))
x = np.pad(a, pad_width=1,mode = 'constant',constant_values =0)
x

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [66]:
x = np.pad(a, pad_width=2,mode = 'constant',constant_values =0)
x

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [67]:
x = np.pad(a, pad_width=1,mode = 'constant',constant_values =2)
x

array([[2., 2., 2., 2., 2.],
       [2., 1., 1., 1., 2.],
       [2., 1., 1., 1., 2.],
       [2., 1., 1., 1., 2.],
       [2., 2., 2., 2., 2.]])

In [68]:
x = np.pad(a, pad_width=1,mode = 'constant',constant_values =(2,3))
x

array([[2., 2., 2., 2., 3.],
       [2., 1., 1., 1., 3.],
       [2., 1., 1., 1., 3.],
       [2., 1., 1., 1., 3.],
       [2., 3., 3., 3., 3.]])

In [69]:
#identity matrix - with just the diagonal elements as one
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [70]:
#Diagonal Matix
np.diag([1,2,5,6,7])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 5, 0, 0],
       [0, 0, 0, 6, 0],
       [0, 0, 0, 0, 7]])

# Operations with numpy array

In [71]:
#asarray - used to convert any datastructure to array
tup=(8,4,6,1,2,3)
tup_arr=np.asarray(tup)
print("Tuple to array:",tup_arr)
print(type(tup))
print(type(tup_arr))

Tuple to array: [8 4 6 1 2 3]
<class 'tuple'>
<class 'numpy.ndarray'>


In [72]:
tup[0]=2

TypeError: 'tuple' object does not support item assignment

In [ ]:
tup_arr[0]=60
print(tup)
print(tup_arr)

### Deep Copy

####  ndarray.copy() mthd creates a deep copy. 
####  It is a complete copy of the array and its data, and doesn’t share with the original array.

In [ ]:
#copy 
arr = np.array([24,12,11])
dup = arr.copy()#Just creates a copy of values and changing in new array does not impact on the org. aray
arr[0] = 55
print(arr)
print(dup)

In [ ]:
dup[1]=55
print(arr)
print(dup)

### View or Shallow Copy

####  ndarray.view() method which is a new array object that looks at the same data of the original array 
####  It shares the original data, and changes in any one of the array will impact other

In [ ]:
#View 
arr = np.array([24,12,11])
x = arr.view()
print(arr)
print(x)

In [ ]:
arr[0] = 55
print(arr)
print(x)

In [ ]:
x[1] = 34
print(arr)
print(x)

In [ ]:
##Itration through an array 

In [ ]:
arr.shape 

In [ ]:
for i in arr: 
    print(i)

In [ ]:
arr_2d

In [ ]:
for row in arr_2d:
    print(row)
    for ele in row:
        print(ele)

In [ ]:
arr_2d.shape

In [ ]:
array_3d.shape

In [ ]:
array_3d.shape

In [ ]:
#Note :How many ever [] u have use that many for loops
for i in array_3d:
    for j in i:
        for k in j:
            print(k)

In [ ]:
#nditer - iterator object 
x = np.arange(4)
y = np.arange(0,8,2)
for a, b in np.nditer([x,y]):
    print(a)
    print(b)

In [ ]:
#Creating a empty numpy array
a=np.empty((0),int)
a

## Addition

In [ ]:
arr1 = np.array(range(1,17,1))
arr1 = arr1.reshape(4,4)

In [ ]:
arr1

In [ ]:
arr2 = np.array(range(10,170,10))
arr2 = arr2.reshape(4,4)

In [ ]:
arr2

In [ ]:
arr1+arr2#adds only if shape are sampe for both numpy arrays

In [ ]:
a = np.array([1,3,4,5])
b = np.array([1,2])

In [ ]:
a+b

In [ ]:
sum_arr = np.add(arr1,arr2)

In [ ]:
print(np.add(arr1,arr2))

In [ ]:
#Subtraction

In [ ]:
arr1-arr2

In [ ]:
print(np.subtract(arr1,arr2))

In [ ]:
#Multiply

In [ ]:
arr1*arr2

In [ ]:
np.multiply(arr1,arr2)

## Matrix Multiplication - np.dot(a1,a2)

In [ ]:
arr1

In [ ]:
arr2

In [ ]:
np.dot(arr1,arr2)

## Divide 

In [ ]:
np.divide(arr1,arr2)

In [ ]:
arr1*100#Broadcast

In [ ]:
arr=np.array(([0.42436315,0.48558583,0.32924763],[0.7439979,0.58220701,0.38213418],[0.5097581,0.34528799,0.1563123]))
print(arr)
print("Replace all elements of the said array with .5 which are greater than .5")
arr[arr>.5]=.5
print(arr)

## Joining  two numpy arrays

In [ ]:
arr1 = np.array([1,2,3,5])
arr2 = np.array([5,6,7,8])
np.stack((arr1,arr2))#adds as rows by default

In [ ]:
np.stack((arr1,arr2),axis=0)

In [ ]:
np.stack((arr1,arr2),axis = 1)#adds as col. by default

In [ ]:
np.hstack((arr1,arr2))#Horizontal stack - adds  into a single row

In [ ]:
#Vstack - Stacks into same column 
np.vstack((arr1,arr2))#appends into vertically-just adds it vertically

In [ ]:
np.concatenate((arr1,arr2))

In [ ]:
z=np.array([1,2,3])
z1=np.array([4,5,6])
print(np.append(z,z1))

In [ ]:
print(np.append(z,z1))

In [ ]:
## Splitting

In [ ]:
arr = np.concatenate((arr1,arr2))
arr

In [ ]:
np.array_split(arr,4)

In [ ]:
np.sort(arr)

In [ ]:
arr = np.array([1,2,3,4,5,60,7])
ele= np.array_split(arr,4)#returns list

In [ ]:
ele

In [ ]:
type(ele)